project:
  type: book

book:
  title: "Title of Your Work"
  author: "Your Name"
  date: "30/06/2025"
  chapters:  # List of chapters in the book, if you have new chapters, add them here
    - index.qmd
    # - intro.qmd
    - chapter1/chapter1.qmd
    # - chapter2/chapter2.qmd
    # - chapter3/chapter3.qmd
    # - chapter4/chapter4.qmd
    # - summary.qmd
    # - references.qmd



format:  # Define the output formats for the book
  html:
    theme:
      - cosmo
      - brand
  pdf:
    # documentclass: scrreprt
    template: format_template\Scholarly Article Template.tex
    keep-tex: true  # Keep the .tex file for debugging

  latex:
    documentclass: book
    template: format_template\Scholarly Article Template.tex
    toc: true  # Enable table of contents in LaTeX
    keep-tex: true  # Keep the .tex file for debugging



